// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: serialization/encode.proto

package serialization

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Results int32

const (
	Results_Ok  Results = 0
	Results_Err Results = 1
)

// Enum value maps for Results.
var (
	Results_name = map[int32]string{
		0: "Ok",
		1: "Err",
	}
	Results_value = map[string]int32{
		"Ok":  0,
		"Err": 1,
	}
)

func (x Results) Enum() *Results {
	p := new(Results)
	*p = x
	return p
}

func (x Results) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Results) Descriptor() protoreflect.EnumDescriptor {
	return file_serialization_encode_proto_enumTypes[0].Descriptor()
}

func (Results) Type() protoreflect.EnumType {
	return &file_serialization_encode_proto_enumTypes[0]
}

func (x Results) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Results.Descriptor instead.
func (Results) EnumDescriptor() ([]byte, []int) {
	return file_serialization_encode_proto_rawDescGZIP(), []int{0}
}

type Book struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookID    string `protobuf:"bytes,1,opt,name=bookID,proto3" json:"bookID,omitempty"`
	BookTitle string `protobuf:"bytes,2,opt,name=bookTitle,proto3" json:"bookTitle,omitempty"`
	BookIsbn  string `protobuf:"bytes,3,opt,name=bookIsbn,proto3" json:"bookIsbn,omitempty"`
}

func (x *Book) Reset() {
	*x = Book{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serialization_encode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_encode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_serialization_encode_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetBookID() string {
	if x != nil {
		return x.BookID
	}
	return ""
}

func (x *Book) GetBookTitle() string {
	if x != nil {
		return x.BookTitle
	}
	return ""
}

func (x *Book) GetBookIsbn() string {
	if x != nil {
		return x.BookIsbn
	}
	return ""
}

type StackedBook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Books []*Book `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
}

func (x *StackedBook) Reset() {
	*x = StackedBook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serialization_encode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StackedBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StackedBook) ProtoMessage() {}

func (x *StackedBook) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_encode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StackedBook.ProtoReflect.Descriptor instead.
func (*StackedBook) Descriptor() ([]byte, []int) {
	return file_serialization_encode_proto_rawDescGZIP(), []int{1}
}

func (x *StackedBook) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

type Books struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Publish *Book   `protobuf:"bytes,1,opt,name=publish,proto3" json:"publish,omitempty"`
	Result  Results `protobuf:"varint,2,opt,name=result,proto3,enum=serialization.Results" json:"result,omitempty"`
}

func (x *Books) Reset() {
	*x = Books{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serialization_encode_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Books) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Books) ProtoMessage() {}

func (x *Books) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_encode_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Books.ProtoReflect.Descriptor instead.
func (*Books) Descriptor() ([]byte, []int) {
	return file_serialization_encode_proto_rawDescGZIP(), []int{2}
}

func (x *Books) GetPublish() *Book {
	if x != nil {
		return x.Publish
	}
	return nil
}

func (x *Books) GetResult() Results {
	if x != nil {
		return x.Result
	}
	return Results_Ok
}

var File_serialization_encode_proto protoreflect.FileDescriptor

var file_serialization_encode_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x73, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x58, 0x0a, 0x04, 0x42,
	0x6f, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x62,
	0x6f, 0x6f, 0x6b, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x62, 0x6f, 0x6f, 0x6b, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x6f, 0x6f,
	0x6b, 0x49, 0x73, 0x62, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x6f, 0x6f,
	0x6b, 0x49, 0x73, 0x62, 0x6e, 0x22, 0x38, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x65, 0x64,
	0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x29, 0x0a, 0x05, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x05, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x22,
	0x66, 0x0a, 0x05, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x2d, 0x0a, 0x07, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x07,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x12, 0x2e, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0x1a, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x6b, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x45, 0x72,
	0x72, 0x10, 0x01, 0x32, 0xf7, 0x01, 0x0a, 0x11, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x50, 0x43, 0x12, 0x34, 0x0a, 0x07, 0x41, 0x64, 0x64,
	0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x13, 0x2e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x1a, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x12,
	0x37, 0x0a, 0x0a, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x13, 0x2e,
	0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x6f,
	0x6f, 0x6b, 0x1a, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x3e, 0x0a, 0x0b, 0x44, 0x69, 0x73, 0x70,
	0x6c, 0x61, 0x79, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x13, 0x2e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x1a, 0x1a, 0x2e, 0x73,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61,
	0x63, 0x6b, 0x65, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x33, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x12, 0x13, 0x2e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x1a, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x42, 0x31, 0x5a,
	0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x69, 0x32,
	0x32, 0x31, 0x30, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x73, 0x68, 0x2d, 0x66, 0x69, 0x65, 0x73,
	0x74, 0x61, 0x2f, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_serialization_encode_proto_rawDescOnce sync.Once
	file_serialization_encode_proto_rawDescData = file_serialization_encode_proto_rawDesc
)

func file_serialization_encode_proto_rawDescGZIP() []byte {
	file_serialization_encode_proto_rawDescOnce.Do(func() {
		file_serialization_encode_proto_rawDescData = protoimpl.X.CompressGZIP(file_serialization_encode_proto_rawDescData)
	})
	return file_serialization_encode_proto_rawDescData
}

var file_serialization_encode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_serialization_encode_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_serialization_encode_proto_goTypes = []interface{}{
	(Results)(0),        // 0: serialization.Results
	(*Book)(nil),        // 1: serialization.Book
	(*StackedBook)(nil), // 2: serialization.StackedBook
	(*Books)(nil),       // 3: serialization.Books
}
var file_serialization_encode_proto_depIdxs = []int32{
	1, // 0: serialization.StackedBook.books:type_name -> serialization.Book
	1, // 1: serialization.Books.publish:type_name -> serialization.Book
	0, // 2: serialization.Books.result:type_name -> serialization.Results
	1, // 3: serialization.LibraryServiceRPC.AddBook:input_type -> serialization.Book
	1, // 4: serialization.LibraryServiceRPC.SearchBook:input_type -> serialization.Book
	1, // 5: serialization.LibraryServiceRPC.DisplayBook:input_type -> serialization.Book
	1, // 6: serialization.LibraryServiceRPC.Delete:input_type -> serialization.Book
	3, // 7: serialization.LibraryServiceRPC.AddBook:output_type -> serialization.Books
	3, // 8: serialization.LibraryServiceRPC.SearchBook:output_type -> serialization.Books
	2, // 9: serialization.LibraryServiceRPC.DisplayBook:output_type -> serialization.StackedBook
	3, // 10: serialization.LibraryServiceRPC.Delete:output_type -> serialization.Books
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_serialization_encode_proto_init() }
func file_serialization_encode_proto_init() {
	if File_serialization_encode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_serialization_encode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Book); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serialization_encode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StackedBook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serialization_encode_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Books); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_serialization_encode_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_serialization_encode_proto_goTypes,
		DependencyIndexes: file_serialization_encode_proto_depIdxs,
		EnumInfos:         file_serialization_encode_proto_enumTypes,
		MessageInfos:      file_serialization_encode_proto_msgTypes,
	}.Build()
	File_serialization_encode_proto = out.File
	file_serialization_encode_proto_rawDesc = nil
	file_serialization_encode_proto_goTypes = nil
	file_serialization_encode_proto_depIdxs = nil
}
