// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: serialization/encode.proto

package serialization

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stacking int32

const (
	Stacking_Up   Stacking = 0
	Stacking_Down Stacking = 1
	Stacking_On   Stacking = 2
)

// Enum value maps for Stacking.
var (
	Stacking_name = map[int32]string{
		0: "Up",
		1: "Down",
		2: "On",
	}
	Stacking_value = map[string]int32{
		"Up":   0,
		"Down": 1,
		"On":   2,
	}
)

func (x Stacking) Enum() *Stacking {
	p := new(Stacking)
	*p = x
	return p
}

func (x Stacking) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stacking) Descriptor() protoreflect.EnumDescriptor {
	return file_serialization_encode_proto_enumTypes[0].Descriptor()
}

func (Stacking) Type() protoreflect.EnumType {
	return &file_serialization_encode_proto_enumTypes[0]
}

func (x Stacking) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Stacking.Descriptor instead.
func (Stacking) EnumDescriptor() ([]byte, []int) {
	return file_serialization_encode_proto_rawDescGZIP(), []int{0}
}

type Results int32

const (
	Results_Ok  Results = 0
	Results_Err Results = 1
)

// Enum value maps for Results.
var (
	Results_name = map[int32]string{
		0: "Ok",
		1: "Err",
	}
	Results_value = map[string]int32{
		"Ok":  0,
		"Err": 1,
	}
)

func (x Results) Enum() *Results {
	p := new(Results)
	*p = x
	return p
}

func (x Results) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Results) Descriptor() protoreflect.EnumDescriptor {
	return file_serialization_encode_proto_enumTypes[1].Descriptor()
}

func (Results) Type() protoreflect.EnumType {
	return &file_serialization_encode_proto_enumTypes[1]
}

func (x Results) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Results.Descriptor instead.
func (Results) EnumDescriptor() ([]byte, []int) {
	return file_serialization_encode_proto_rawDescGZIP(), []int{1}
}

type Book struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookID          string `protobuf:"bytes,1,opt,name=bookID,proto3" json:"bookID,omitempty"`
	BookTitle       string `protobuf:"bytes,2,opt,name=bookTitle,proto3" json:"bookTitle,omitempty"`
	BookIsbn        string `protobuf:"bytes,3,opt,name=bookIsbn,proto3" json:"bookIsbn,omitempty"`
	BookAuthor      string `protobuf:"bytes,4,opt,name=bookAuthor,proto3" json:"bookAuthor,omitempty"`
	BookPublishDate string `protobuf:"bytes,5,opt,name=bookPublishDate,proto3" json:"bookPublishDate,omitempty"`
}

func (x *Book) Reset() {
	*x = Book{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serialization_encode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_encode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_serialization_encode_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetBookID() string {
	if x != nil {
		return x.BookID
	}
	return ""
}

func (x *Book) GetBookTitle() string {
	if x != nil {
		return x.BookTitle
	}
	return ""
}

func (x *Book) GetBookIsbn() string {
	if x != nil {
		return x.BookIsbn
	}
	return ""
}

func (x *Book) GetBookAuthor() string {
	if x != nil {
		return x.BookAuthor
	}
	return ""
}

func (x *Book) GetBookPublishDate() string {
	if x != nil {
		return x.BookPublishDate
	}
	return ""
}

type StackedBook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stackedover *Book `protobuf:"bytes,1,opt,name=stackedover,proto3" json:"stackedover,omitempty"`
}

func (x *StackedBook) Reset() {
	*x = StackedBook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serialization_encode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StackedBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StackedBook) ProtoMessage() {}

func (x *StackedBook) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_encode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StackedBook.ProtoReflect.Descriptor instead.
func (*StackedBook) Descriptor() ([]byte, []int) {
	return file_serialization_encode_proto_rawDescGZIP(), []int{1}
}

func (x *StackedBook) GetStackedover() *Book {
	if x != nil {
		return x.Stackedover
	}
	return nil
}

type Books struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Publish   *Book    `protobuf:"bytes,1,opt,name=publish,proto3" json:"publish,omitempty"`
	Result    Results  `protobuf:"varint,2,opt,name=result,proto3,enum=serialization.Results" json:"result,omitempty"`
	Operation Stacking `protobuf:"varint,3,opt,name=Operation,proto3,enum=serialization.Stacking" json:"Operation,omitempty"`
}

func (x *Books) Reset() {
	*x = Books{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serialization_encode_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Books) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Books) ProtoMessage() {}

func (x *Books) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_encode_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Books.ProtoReflect.Descriptor instead.
func (*Books) Descriptor() ([]byte, []int) {
	return file_serialization_encode_proto_rawDescGZIP(), []int{2}
}

func (x *Books) GetPublish() *Book {
	if x != nil {
		return x.Publish
	}
	return nil
}

func (x *Books) GetResult() Results {
	if x != nil {
		return x.Result
	}
	return Results_Ok
}

func (x *Books) GetOperation() Stacking {
	if x != nil {
		return x.Operation
	}
	return Stacking_Up
}

type EmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serialization_encode_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_encode_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_serialization_encode_proto_rawDescGZIP(), []int{3}
}

var File_serialization_encode_proto protoreflect.FileDescriptor

var file_serialization_encode_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x73, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xa2, 0x01, 0x0a, 0x04,
	0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09,
	0x62, 0x6f, 0x6f, 0x6b, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x6f,
	0x6f, 0x6b, 0x49, 0x73, 0x62, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x6f,
	0x6f, 0x6b, 0x49, 0x73, 0x62, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x6f, 0x6f, 0x6b,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x28, 0x0a, 0x0f, 0x62, 0x6f, 0x6f, 0x6b, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x44, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x62, 0x6f, 0x6f, 0x6b, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x44, 0x61, 0x74, 0x65,
	0x22, 0x44, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x12,
	0x35, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x63, 0x6b,
	0x65, 0x64, 0x6f, 0x76, 0x65, 0x72, 0x22, 0x9d, 0x01, 0x0a, 0x05, 0x42, 0x6f, 0x6f, 0x6b, 0x73,
	0x12, 0x2d, 0x0a, 0x07, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x07, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x12,
	0x2e, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x16, 0x2e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x35, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x17, 0x2e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x09, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2a, 0x24, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x69,
	0x6e, 0x67, 0x12, 0x06, 0x0a, 0x02, 0x55, 0x70, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x6f,
	0x77, 0x6e, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x6e, 0x10, 0x02, 0x2a, 0x1a, 0x0a, 0x07,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x6b, 0x10, 0x00, 0x12,
	0x07, 0x0a, 0x03, 0x45, 0x72, 0x72, 0x10, 0x01, 0x32, 0xc2, 0x02, 0x0a, 0x11, 0x4c, 0x69, 0x62,
	0x72, 0x61, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x50, 0x43, 0x12, 0x34,
	0x0a, 0x07, 0x41, 0x64, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x13, 0x2e, 0x73, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x1a, 0x14,
	0x2e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x42,
	0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x37, 0x0a, 0x0a, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x6f,
	0x6f, 0x6b, 0x12, 0x13, 0x2e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x1a, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x46, 0x0a,
	0x0b, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x1b, 0x2e, 0x73,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x65,
	0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x33, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x13, 0x2e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x42, 0x6f, 0x6f, 0x6b, 0x1a, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x41, 0x0a, 0x0e, 0x53, 0x65,
	0x74, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x13, 0x2e, 0x73,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x6f, 0x6f,
	0x6b, 0x1a, 0x1a, 0x2e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x42, 0x31, 0x5a,
	0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x69, 0x32,
	0x32, 0x31, 0x30, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x73, 0x68, 0x2d, 0x66, 0x69, 0x65, 0x73,
	0x74, 0x61, 0x2f, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_serialization_encode_proto_rawDescOnce sync.Once
	file_serialization_encode_proto_rawDescData = file_serialization_encode_proto_rawDesc
)

func file_serialization_encode_proto_rawDescGZIP() []byte {
	file_serialization_encode_proto_rawDescOnce.Do(func() {
		file_serialization_encode_proto_rawDescData = protoimpl.X.CompressGZIP(file_serialization_encode_proto_rawDescData)
	})
	return file_serialization_encode_proto_rawDescData
}

var file_serialization_encode_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_serialization_encode_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_serialization_encode_proto_goTypes = []interface{}{
	(Stacking)(0),        // 0: serialization.Stacking
	(Results)(0),         // 1: serialization.Results
	(*Book)(nil),         // 2: serialization.Book
	(*StackedBook)(nil),  // 3: serialization.StackedBook
	(*Books)(nil),        // 4: serialization.Books
	(*EmptyRequest)(nil), // 5: serialization.EmptyRequest
}
var file_serialization_encode_proto_depIdxs = []int32{
	2, // 0: serialization.StackedBook.stackedover:type_name -> serialization.Book
	2, // 1: serialization.Books.publish:type_name -> serialization.Book
	1, // 2: serialization.Books.result:type_name -> serialization.Results
	0, // 3: serialization.Books.Operation:type_name -> serialization.Stacking
	2, // 4: serialization.LibraryServiceRPC.AddBook:input_type -> serialization.Book
	2, // 5: serialization.LibraryServiceRPC.SearchBook:input_type -> serialization.Book
	5, // 6: serialization.LibraryServiceRPC.DisplayBook:input_type -> serialization.EmptyRequest
	2, // 7: serialization.LibraryServiceRPC.Delete:input_type -> serialization.Book
	2, // 8: serialization.LibraryServiceRPC.SetStackedBook:input_type -> serialization.Book
	4, // 9: serialization.LibraryServiceRPC.AddBook:output_type -> serialization.Books
	4, // 10: serialization.LibraryServiceRPC.SearchBook:output_type -> serialization.Books
	3, // 11: serialization.LibraryServiceRPC.DisplayBook:output_type -> serialization.StackedBook
	4, // 12: serialization.LibraryServiceRPC.Delete:output_type -> serialization.Books
	3, // 13: serialization.LibraryServiceRPC.SetStackedBook:output_type -> serialization.StackedBook
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_serialization_encode_proto_init() }
func file_serialization_encode_proto_init() {
	if File_serialization_encode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_serialization_encode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Book); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serialization_encode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StackedBook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serialization_encode_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Books); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serialization_encode_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_serialization_encode_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_serialization_encode_proto_goTypes,
		DependencyIndexes: file_serialization_encode_proto_depIdxs,
		EnumInfos:         file_serialization_encode_proto_enumTypes,
		MessageInfos:      file_serialization_encode_proto_msgTypes,
	}.Build()
	File_serialization_encode_proto = out.File
	file_serialization_encode_proto_rawDesc = nil
	file_serialization_encode_proto_goTypes = nil
	file_serialization_encode_proto_depIdxs = nil
}
